"""Independent Replay Verifier for GridWise Energy Optimizer.

Simulates the 24-hour dispatch schedule against strict energy conservation,
battery dynamics, operational limits, and directive constraints.
Recomputes total summary metrics to ensure 100% calculation integrity.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional
from app.schemas import (
    BatteryInfo,
    DirectiveInterpretation,
    HourEntry,
    HourlyPlanEntry,
    OptimizeEnergyRequest,
)


@dataclass
class ReplayVerificationResult:
    """Outcome of independent schedule verification."""
    is_valid: bool
    errors: List[str]
    total_grid_kwh: float
    total_cost_bdt: float
    peak_grid_kwh: float


def verify_and_recalculate_schedule(
    request: OptimizeEnergyRequest,
    directives: List[DirectiveInterpretation],
    hourly_plan: List[HourlyPlanEntry],
    tolerance: float = 0.01,
) -> ReplayVerificationResult:
    """Perform independent physical replay check and exact recalculation of totals.

    Args:
        request: The original optimization request containing 24h demand, solar, tariffs, and battery specs.
        directives: List of validated directive interpretations.
        hourly_plan: List of 24 hourly dispatch entries generated by the solver.
        tolerance: Numerical tolerance for floating-point balance comparisons (default 0.01).

    Returns:
        ReplayVerificationResult with validity status, error list, and verified metrics.
    """
    errors: List[str] = []

    # 1. Structural Check
    if len(hourly_plan) != 24:
        errors.append(f"Expected exactly 24 hourly plan entries, got {len(hourly_plan)}.")
        return ReplayVerificationResult(
            is_valid=False,
            errors=errors,
            total_grid_kwh=0.0,
            total_cost_bdt=0.0,
            peak_grid_kwh=0.0,
        )

    # 2. Extract Effective Constraints from Directives
    solar_factors: Dict[int, float] = {h: 1.0 for h in range(24)}
    min_reserves: Dict[int, float] = {h: request.battery.minimum_energy_kwh for h in range(24)}
    no_charge_hours: set = set()
    no_discharge_hours: set = set()
    grid_caps: Dict[int, float] = {}

    for d in directives:
        if not d.applies or not d.structured_adjustment:
            continue

        adj = d.structured_adjustment
        adj_hours = adj.get("hours", [])

        if d.directive_type == "solar_reduction":
            factor = float(adj.get("factor", 1.0))
            for h in adj_hours:
                if 0 <= h < 24:
                    solar_factors[h] = min(solar_factors[h], factor)

        elif d.directive_type == "minimum_battery_reserve":
            req_min = float(adj.get("minimum_energy_kwh", request.battery.minimum_energy_kwh))
            for h in adj_hours:
                if 0 <= h < 24:
                    min_reserves[h] = max(min_reserves[h], req_min)

        elif d.directive_type == "no_charge_window":
            for h in adj_hours:
                if 0 <= h < 24:
                    no_charge_hours.add(h)

        elif d.directive_type == "no_discharge_window":
            for h in adj_hours:
                if 0 <= h < 24:
                    no_discharge_hours.add(h)

        elif d.directive_type == "max_grid_window":
            cap = float(adj.get("max_grid_kwh", float("inf")))
            for h in adj_hours:
                if 0 <= h < 24:
                    grid_caps[h] = min(grid_caps.get(h, float("inf")), cap)

    # 3. Simulate Hour-by-Hour
    battery_level = request.battery.initial_energy_kwh
    calculated_total_grid = 0.0
    calculated_total_cost = 0.0
    calculated_peak_grid = 0.0

    for h in range(24):
        plan = hourly_plan[h]
        req_hour = request.hours[h]

        if plan.hour != h:
            errors.append(f"Hour mismatch at index {h}: plan specifies hour {plan.hour}.")

        grid = plan.grid_kwh
        solar_used = plan.solar_used_kwh
        action = plan.battery_action
        bat_kwh = plan.battery_kwh
        energy_after = plan.battery_energy_after_kwh

        charge_kwh = bat_kwh if action == "charge" else 0.0
        discharge_kwh = bat_kwh if action == "discharge" else 0.0

        if action == "idle" and bat_kwh > tolerance:
            errors.append(f"Hour {h}: battery_action is 'idle' but battery_kwh is {bat_kwh:.3f} > 0.")

        # Metric accumulators
        calculated_total_grid += grid
        calculated_total_cost += grid * req_hour.tariff_bdt_per_kwh
        if grid > calculated_peak_grid:
            calculated_peak_grid = grid

        # A. Energy Balance: grid + solar_used + discharge == demand + charge
        supply = grid + solar_used + discharge_kwh
        demand = req_hour.demand_kwh + charge_kwh
        if abs(supply - demand) > tolerance:
            errors.append(
                f"Hour {h}: Energy balance violation. Supply ({supply:.3f}) != Demand ({demand:.3f}), "
                f"diff={abs(supply - demand):.4f} > {tolerance}"
            )

        # B. Solar Availability & Curtailment: solar_used <= effective_solar
        max_solar = req_hour.solar_kwh * solar_factors[h]
        if solar_used > max_solar + tolerance:
            errors.append(
                f"Hour {h}: Solar overutilization. solar_used ({solar_used:.3f}) > effective solar ({max_solar:.3f})."
            )

        # C. Battery Rate Limits
        if charge_kwh > request.battery.max_charge_kwh_per_hour + tolerance:
            errors.append(
                f"Hour {h}: Charge rate ({charge_kwh:.3f}) exceeds max_charge ({request.battery.max_charge_kwh_per_hour})."
            )
        if discharge_kwh > request.battery.max_discharge_kwh_per_hour + tolerance:
            errors.append(
                f"Hour {h}: Discharge rate ({discharge_kwh:.3f}) exceeds max_discharge ({request.battery.max_discharge_kwh_per_hour})."
            )

        # D. Battery Capacity & Dynamic Reserve Limits
        expected_energy_after = battery_level + charge_kwh - discharge_kwh
        if abs(energy_after - expected_energy_after) > tolerance:
            errors.append(
                f"Hour {h}: Battery transition mismatch. Reported E_after={energy_after:.3f}, "
                f"calculated={expected_energy_after:.3f}."
            )

        if energy_after > request.battery.capacity_kwh + tolerance:
            errors.append(
                f"Hour {h}: Battery energy ({energy_after:.3f}) exceeds capacity ({request.battery.capacity_kwh})."
            )
        if energy_after < min_reserves[h] - tolerance:
            errors.append(
                f"Hour {h}: Battery energy ({energy_after:.3f}) below required reserve ({min_reserves[h]:.3f})."
            )

        # E. Directives Compliance
        if h in no_charge_hours and charge_kwh > tolerance:
            errors.append(f"Hour {h}: Charged ({charge_kwh:.3f} kWh) during active no_charge_window.")

        if h in no_discharge_hours and discharge_kwh > tolerance:
            errors.append(f"Hour {h}: Discharged ({discharge_kwh:.3f} kWh) during active no_discharge_window.")

        if h in grid_caps and grid > grid_caps[h] + tolerance:
            errors.append(
                f"Hour {h}: Grid import ({grid:.3f}) exceeds max_grid cap ({grid_caps[h]:.3f})."
            )

        battery_level = energy_after

    # 4. End-of-Day Neutrality Check
    if abs(battery_level - request.battery.initial_energy_kwh) > tolerance:
        errors.append(
            f"End-of-day battery neutrality violated: Final energy ({battery_level:.3f}) != "
            f"Initial energy ({request.battery.initial_energy_kwh:.3f})."
        )

    return ReplayVerificationResult(
        is_valid=len(errors) == 0,
        errors=errors,
        total_grid_kwh=round(calculated_total_grid, 2),
        total_cost_bdt=round(calculated_total_cost, 2),
        peak_grid_kwh=round(calculated_peak_grid, 2),
    )
